
name: Toi chi muon deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run 'docker compose'
      run: docker compose -f compose.yaml up --build -d
      working-directory: /home/vitien/actions-runner/_work/Opal_Project_BE/Opal_Project_BE/Opal_Exe201/
