name: Deploy Opal

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Check if compose.yaml exists
        run: ls -al /home/ubuntu/actions-runner/_work/Opal_Project_BE/Opal_Project_BE/Opal_Exe201/

      - name: Run 'docker compose'
        run: docker compose -f /home/ubuntu/actions-runner/_work/Opal_Project_BE/Opal_Project_BE/Opal_Exe201/compose.yaml up --build -d
