name: Deploy Opal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  docker-compose:
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install Docker Buildx
      run: |
        mkdir -p ~/.docker/cli-plugins/
        curl -SL https://github.com/docker/buildx/releases/download/v0.10.0/buildx-v0.10.0.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
        chmod +x ~/.docker/cli-plugins/docker-buildx

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create builder
      run: docker buildx create --use

    - name: Run 'docker compose'
      run: docker compose up --build -d
