name: toi muon duoc deployyyy

on:
  push:
    branches:
      - main
      
jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Run 'docker compose'
      run: docker compose up --build -d
