name: Deploy Opal

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  docker-compose:
    runs-on: self-hosted  # Kiểm tra runner có nhãn này
    steps:
    - name: Check out code
      uses: actions/checkout@v3  # Sử dụng phiên bản mới nhất của checkout

    - name: Set up Docker Buildx  # Optional: Set up Docker Buildx for multi-platform builds
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub  # Nếu cần đăng nhập Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Run 'docker compose'
      run: docker compose up --build -d
