name: Tôi muốn được deployyyy

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: List work directory
      run: ls -al /home/ubuntu/actions-runner/actions-runner/_work

    - name: Run 'docker compose'
      run: docker compose -f /home/ubuntu/actions-runner/actions-runner/_work/Opal_Project_BE/Opal_Exe201/compose.yaml up --build -d
